version: '3'

services: 
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      
  db: 
    image: bitnami/mongodb:4.4
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=123456
      - MONGODB_DATABASE=nest
  
volumes:
  mongodb_data:
    driver: local